### ISSUE TITLE
Default skybox not working

### ISSUE THREAD

**Issue by MarioMario456** [CloneTrooper1019/Roblox-2008-Client#2]
Hello, so there's an issue in the client. On all graphical modes (except OpenGL Legacy) the default skybox doesn't work, instead being plain white. Here's a screenshot (taken in Direct3D mode):
![look](https://user-images.githubusercontent.com/27364420/62256173-32e4c880-b3ce-11e9-93e0-2f4bd0fd0f27.png)

**Comment by MaximumADHD** [comment]
Hi there. As I mentioned previously, I do not have the source code to this build of Roblox, so I cannot fix this issue.

**Comment by MarioMario456** [comment]
The source code is completely lost, but we have access to the binary itself. You can hex-edit it until you find the problem.

**Comment by MarioMario456** [comment]
Apparently the skybox doesn't show up in all video modes except "OpenGL Legacy" if the installation path has spaces on it. Might suggest that pre-2009 clients were installed in "C:\ROBLOX\Versions\version-xxxxxxxxxxxxxxxx" instead of "C:\Program Files\ROBLOX Corporation\ROBLOX\Versions\version-xxxxxxxxxxxxxxxx". You should patch the executable for the skybox to work in all video modes except "OpenGL Legacy" if the installation path has spaces on it with a hex editor like HxD. After patched, close this thread.

**Comment by MarioMario456** [comment]
no replys in days, closing
